### ISSUE TITLE
Keep inline comment where it is

### ISSUE THREAD

**Issue by alessandro-newzoo** [mblander/formate#25]
Hi, and thanks for this fantastic extension!

I have only one issue with it:

In my LESS files, I often put an inline comment next to a closing bracket, so I know what it relates to:

```less
	.popup-body {

		display: block;

	} // .popup-body <--------
```

But unfortunately Formate breaks it when I format the document, and puts it on a new line:

```less
	.popup-body {

		display: block;

	}

        // .popup-body <--------
```

Is there any way to prevent this from happening please?
